name: Docs
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # Builds docs using sphinx
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install .[doc]"
        docs-folder: "docs/"

    - uses: actions/upload-artifact@v2
      with:
        name: ApiDocsHTML
        path: "docs/_build/html/"
